spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jdbc
#    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always # ??? 2.5 ?? ?? - sql ??? ???? ?? ??

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace